---
# tasks file for common
- name: install libselinux-python
  yum:
    name: libselinux-python
    state: latest

- name: update
  yum:
    name: '*'
    state: latest

- name: install chrony
  yum:
    name: chrony
    state: latest

- name: disable selinux
  selinux:
    policy: targeted
    state: permissive
